Forked update

diff --git a/pihole-cloudsync b/pihole-cloudsync
--- a/pihole-cloudsync
+++ b/pihole-cloudsync
@@ -33,14 +33,23 @@ update='December 26, 2020'
 ###########################################################################
 # CONSTANTS
 personal_git_dir='/usr/local/bin/my-pihole-lists'
-pihole_dir='/etc/pihole'
-gravity_db='/etc/pihole/gravity.db'
-dnsmasq_dir='/etc/dnsmasq.d/'
+pihole_dir=${pihole_base_dir}'/etc/pihole'
+gravity_db=${pihole_dir}'/gravity.db'
+dnsmasq_dir=${pihole_base_dir}'/etc/dnsmasq.d/'
 ad_list='adlist.csv'
 custom_list='custom.list'
 domain_list='domainlist.csv'
 cname_list='05-pihole-custom-cname.conf'
+docker_container_name='pihole'
 ###########################################################################
+
+container_status=$( docker ps -q -f name="${docker_container_name}")
+if [[ -n "$container_status" ]]; then
+    docker_command='docker exec pihole'
+else
+    docker_command=""
+fi
+
 # SHOULDN'T NEED TO EDIT BELOW THIS LINE
 
 # Force sudo if not running with root privileges
@@ -85,7 +94,7 @@ pull_initialize () {
 	$SUDO git reset --hard origin/master -q
 
 	# Stop DNS server
-	$SUDO service pihole-FTL stop
+    $SUDO $docker_command service pihole-FTL stop
 
 	# Overwrite local files
 	$SUDO cp $custom_list $pihole_dir
@@ -98,7 +107,7 @@ pull_initialize () {
 	$SUDO sqlite3 $gravity_db -header -csv ".import domainlist.csv domainlist"
 
 	# Restart Pi-hole to pick up changes
-	$SUDO pihole -g
+    $SUDO $docker_command pihole -g
 
 	# Display success messages
 	echo "Local Pi-hole initialized in Pull mode and first pull successfully completed.";
@@ -108,35 +117,35 @@ push () {
 	 # Go to Pi-hole directory, exit if doesn't exist
 	cd $pihole_dir || exit
 
-        # Copy local Custom and CNAME lists to local Git repo
-        $SUDO cp $custom_list $personal_git_dir
-        $SUDO cp $dnsmasq_dir/$cname_list $personal_git_dir
+    # Copy local Custom and CNAME lists to local Git repo
+    $SUDO cp $custom_list $personal_git_dir
+    $SUDO cp $dnsmasq_dir/$cname_list $personal_git_dir
 
 	# Go to local Git repo directory
-        cd $personal_git_dir || exit
+    cd $personal_git_dir || exit
 
-        # Export Ad and Domain lists from Gravity database
-        $SUDO sqlite3 $gravity_db -header -csv "SELECT * FROM adlist" >$ad_list
-        $SUDO sqlite3 $gravity_db -header -csv "SELECT * FROM domainlist" >$domain_list
+    # Export Ad and Domain lists from Gravity database
+    $SUDO sqlite3 $gravity_db -header -csv "SELECT * FROM adlist" >$ad_list
+    $SUDO sqlite3 $gravity_db -header -csv "SELECT * FROM domainlist" >$domain_list
 
 	# Compare local files to remote Git repo
 	$SUDO git remote update > /dev/null
 
 	# If local files are different than remote, update remote Git repo
-        CHANGED=$($SUDO git --work-tree=$personal_git_dir status --porcelain)
-        if [ -n "${CHANGED}" ]; then
-                echo 'Local Pi-hole lists are different than remote Git repo. Updating remote repo...';
+    CHANGED=$($SUDO git --work-tree=$personal_git_dir status --porcelain)
+    if [ -n "${CHANGED}" ]; then
+        echo 'Local Pi-hole lists are different than remote Git repo. Updating remote repo...';
 		rightnow=$(date +"%B %e, %Y %l:%M%p")
 		# Remove -q option if you don't want to run in "quiet" mode
 		$SUDO git commit -a -m "Updated $rightnow" -q
 		$SUDO git push -q
 		echo 'Done!';
 		exit 0
-        else
-	# If local files are the same as remote, do nothing and exit
-	echo 'Remote Git repo matches local Pi-hole lists. No further action required.';
+    else
+	    # If local files are the same as remote, do nothing and exit
+	    echo 'Remote Git repo matches local Pi-hole lists. No further action required.';
 		exit 0
-        fi
+    fi
 }
 pull () {
         # Go to Pi-hole directory, exit if doesn't exist
@@ -146,24 +155,24 @@ pull () {
 	$SUDO git remote update > /dev/null
 	CHANGED=$($SUDO git log HEAD..origin/master --oneline)
 	if [ -n "${CHANGED}" ]; then
-                echo 'Remote Git repo is different than local Pi-hole lists. Updating local lists...';
-                # Remove -q option if you don't want to run in "quiet" mode
-                $SUDO git fetch --all -q
+        echo 'Remote Git repo is different than local Pi-hole lists. Updating local lists...';
+        # Remove -q option if you don't want to run in "quiet" mode
+        $SUDO git fetch --all -q
 		$SUDO git reset --hard origin/master -q
-                $SUDO service pihole-FTL stop
-                $SUDO cp $custom_list $pihole_dir
-                $SUDO cp $cname_list $dnsmasq_dir
-                $SUDO sqlite3 $gravity_db "DROP TABLE adlist;"
-                $SUDO sqlite3 $gravity_db -header -csv ".import adlist.csv adlist"
-                $SUDO sqlite3 $gravity_db "DROP TABLE domainlist;"
-                $SUDO sqlite3 $gravity_db -header -csv ".import domainlist.csv domainlist"
-		$SUDO pihole -g
-                echo 'Done!';
-                exit 0
-        else
-                echo 'Local Pi-hole lists match remote Git repo. No further action required.';
-                exit 0
-        fi
+        $SUDO $docker_command service pihole-FTL stop
+        $SUDO cp $custom_list $pihole_dir
+        $SUDO cp $cname_list $dnsmasq_dir
+        $SUDO sqlite3 $gravity_db "DROP TABLE adlist;"
+        $SUDO sqlite3 $gravity_db -header -csv ".import adlist.csv adlist"
+        $SUDO sqlite3 $gravity_db "DROP TABLE domainlist;"
+        $SUDO sqlite3 $gravity_db -header -csv ".import domainlist.csv domainlist"
+        $SUDO $docker_command pihole -g
+        echo 'Done!';
+        exit 0
+    else
+        echo 'Local Pi-hole lists match remote Git repo. No further action required.';
+        exit 0
+    fi
 }
 ###########################################################################
 # Check to see whether a command line option was provided
@@ -178,26 +187,26 @@ do
     # Initialize - adds primary Pi-hole's lists to local Git repo before first push/upload
     if [ "$arg" == "--initpush" ]
     then
-	echo "$arg option detected. Initializing local Git repo for Push/Upload.";
-	push_initialize
-	exit 0
+	    echo "$arg option detected. Initializing local Git repo for Push/Upload.";
+	    push_initialize
+	    exit 0
     # Initialize - adds primary Pi-hole's lists to local Git repo before first push/upload
     elif [ "$arg" == "--initpull" ]
     then
-	echo "$arg option detected. Initializing local Git repo for Pull/Download.";
-	pull_initialize
-	exit 0
+	    echo "$arg option detected. Initializing local Git repo for Pull/Download.";
+	    pull_initialize
+	    exit 0
     # Push / Upload - Pushes updated local Pi-hole lists to remote Git repo
     elif [ "$arg" == "--push" ] || [ "$arg" == "--upload" ] || [ "$arg" == "--up" ] || [ "$arg" == "-u" ]
     then
-	echo "$arg option detected. Running in Push/Upload mode."
-	push
-	exit 0
+	    echo "$arg option detected. Running in Push/Upload mode."
+	    push
+	    exit 0
     # Pull / Download - Pulls updated Pi-hole lists from remote Git repo
     elif [ "$arg" == "--pull" ] || [ "$arg" == "--download" ] || [ "$arg" == "--down" ]|| [ "$arg" == "-d" ]
     then
         echo "$arg option detected. Running in Pull/Download mode."
-	pull
+	    pull
         exit 0
     # Help - Displays help dialog
     elif [ "$arg" == "--help" ] || [ "$arg" == "-h" ] || [ "$arg" == "-?" ]
@@ -223,12 +232,12 @@ EOF
     # Version - Displays version number
     elif [ "$arg" == "--version" ] || [ "$arg" == "-v" ]
 	then
-	echo 'pihole-cloudsync v'$version' - Updated '"$update";
-	echo 'https://github.com/stevejenkins/pihole-cloudsync';
+	    echo 'pihole-cloudsync v'$version' - Updated '"$update";
+	    echo 'https://github.com/stevejenkins/pihole-cloudsync';
 
     # Invalid command line option was passed
     else
-	echo "Invalid command line option. Try --push, --pull, or --help."
-	exit 1
+	    echo "Invalid command line option. Try --push, --pull, or --help."
+	    exit 1
     fi
 done
